@startuml
!include style.puml
skinparam ArrowFontStyle plain
box Logic LOGIC_COLOR_T1
participant "l:Logic" as CreateCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":ImmuniMate" as ImmuniMate MODEL_COLOR
participant ":UniquePersonList" as UniquePersonList MODEL_COLOR
participant "internalList: ObservableList<Person>" as internalList MODEL_COLOR
participant "p1:Person" as p1 MODEL_COLOR
end box

[-> CreateCommand : execute()
activate CreateCommand

CreateCommand -> ModelManager : getFilteredPersonsList()
activate ModelManager

ModelManager --> CreateCommand : persons
deactivate ModelManager

CreateCommand -> ModelManager : hasPerson(...)
activate ModelManager

ModelManager -> ImmuniMate: hasPerson(p1)
activate ImmuniMate

ImmuniMate -> UniquePersonList : contains(p1)
activate UniquePersonList

UniquePersonList -> internalList : stream().anyMatch(p1::isSamePerson)
activate internalList

internalList -> p1 : isSamePerson(p1)
activate p1

p1 --> internalList : true
deactivate p1

internalList --> UniquePersonList : true
deactivate internalList

UniquePersonList --> ImmuniMate : true
deactivate UniquePersonList

ImmuniMate --> ModelManager : true
deactivate ImmuniMate

ModelManager --> CreateCommand : true
deactivate ModelManager

CreateCommand -> p1 : setEmail(null)
activate p1

p1 --> CreateCommand
deactivate p1

[<--CreateCommand
deactivate CreateCommand

@enduml
