@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ImmuniMateParser" as ImmuniMateParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete S1234567X")
activate LogicManager

LogicManager -> ImmuniMateParser : parseCommand("delete S1234567X")
activate ImmuniMateParser

create DeleteCommandParser
ImmuniMateParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ImmuniMateParser
deactivate DeleteCommandParser

ImmuniMateParser -> DeleteCommandParser : parse("S1234567X")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser :
deactivate DeleteCommand

DeleteCommandParser --> ImmuniMateParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ImmuniMateParser
destroy DeleteCommandParser

ImmuniMateParser --> LogicManager : d
deactivate ImmuniMateParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : hasPerson(...)
activate Model
Model --> DeleteCommand : true
deactivate Model
DeleteCommand -> Model : deletePerson(...)
activate Model
Model --> DeleteCommand : delete specified person
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
