@startuml
!include style.puml
skinparam ArrowFontStyle plain
box Logic LOGIC_COLOR_T1
participant "l:Logic" as CreateCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":ImmuniMate" as ImmuniMate MODEL_COLOR
participant ":UniquePersonList" as UniquePersonList MODEL_COLOR
participant "internalList: ObservableList<Person>" as internalList MODEL_COLOR
participant "p1:Person" as p1 MODEL_COLOR
participant "p1:Person" as p MODEL_COLOR
end box

[-> CreateCommand : execute()
activate CreateCommand

CreateCommand -> ModelManager : hasPerson(...)
activate ModelManager

ModelManager -> ImmuniMate: hasPerson(p1)
activate ImmuniMate

ImmuniMate -> UniquePersonList : contains(p1)
activate UniquePersonList

UniquePersonList -> internalList : stream().anyMatch(p1::isSamePerson)
activate internalList

internalList -> p1 : isSamePerson(p1)
activate p1

p1 --> internalList
deactivate p1

internalList --> UniquePersonList
deactivate internalList

UniquePersonList --> ImmuniMate
deactivate UniquePersonList

ImmuniMate --> ModelManager
deactivate ImmuniMate

ModelManager --> CreateCommand
deactivate ModelManager

CreateCommand -> ModelManager : setEmail(...)
activate ModelManager

ModelManager -> ImmuniMate: getPerson(...)
activate ImmuniMate

ImmuniMate -> UniquePersonList : get(...)
activate UniquePersonList

UniquePersonList -> internalList : get(...)
activate internalList

internalList --> UniquePersonList : p
deactivate internalList

UniquePersonList --> ImmuniMate : p
deactivate UniquePersonList

ImmuniMate -> p : setEmail(null)
activate p
p --> ImmuniMate : set email to null
deactivate p

ImmuniMate --> ModelManager
deactivate ImmuniMate

ModelManager --> CreateCommand
deactivate ModelManager

[<--CreateCommand
deactivate CreateCommand

@enduml
