@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyImmuniMate" as ReadOnlyImmuniMate
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class ImmuniMate
Class ModelManager
Class UserPrefs
Class UniquePersonList
Class UniqueVisitList
Class Person
Class Address
Class Name
Class Phone
Class Nric
Class DateOfBirth
Class Sex
Class Status
Class Email
Class Country
Class Allergies
Class BloodType
Class Condition
Class DateOfAdmission
Class Diagnosis
Class Symptom
Class Visit
Class DateOfVisit


Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ImmuniMate .up.|> ReadOnlyImmuniMate

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyImmuniMate
ModelManager -left-> "1" ImmuniMate
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ImmuniMate *--> "1" UniquePersonList
ImmuniMate *--> "1" UniqueVisitList
UniquePersonList --> "~* all" Person
UniqueVisitList --> "~* all" Visit
Person *--> "1" Nric
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Address
Person *--> "1" DateOfBirth
Person *--> "1" Sex
Person *--> "1" Status

Person *--> "0..1" Email
Person *--> "0..1" Country
Person *--> "0..1" Allergies
Person *--> "0..1" BloodType
Person *--> "0..1" Condition
Person *--> "0..1" DateOfAdmission
Person *--> "0..1" Diagnosis
Person *--> "0..1" Symptom

Visit *--> "1" DateOfVisit
Visit *--> "1" Nric
Visit *--> "1" Diagnosis
Visit *--> "1" Symptom
Visit *--> "1" Status


Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Nric -[hidden]right-> Name
Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> DateOfBirth
DateOfBirth -[hidden]right-> Sex
Sex -[hidden]right-> Status

ModelManager --> "~* filtered" Person
ModelManager --> "~* filtered" Visit
@enduml

